language: go

go:
 - 1.8
 - 1.9

before_install:
 - go get -v github.com/urfave/cli
 - go get -v github.com/gorilla/mux

script:
 - cd src/ifconfig-cli && go test ./...
 - cd src/ifconfig-service && go test ./...
