language: go

go:
 - 1.8
 - 1.9

before_install:
 - make

script:
 - go test ./...

after_success:
 - docker build -t "$DOCKER_USERNAME"/ifconfig-cli ifconfig-cli
 - docker build -t "$DOCKER_USERNAME"/ifconfig-service ifconfig-service
 - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
 - docker push "$DOCKER_USERNAME"/ifconfig-service
 - docker push "$DOCKER_USERNAME"/ifconfig-cli
